apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-conf
  namespace: default
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2020-05-15
        store: bigtable
        object_store: gcs
        schema: v11
        index:
          prefix: loki_index_
          period: 168h
    storage_config:
      bigtable:
        instance: BIGTABLE_INSTANCE
        project: BIGTABLE_PROJECT
      gcs:
        bucket_name: GCS_BUCKET_NAME
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h