apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: default
  labels:
    app: loki
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki