apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    component: query-layer
    name: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      component: query-layer
      name: thanos-query
  template:
    metadata:
      labels:
        component: query-layer
        name: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.13.0-rc.0
        args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --log.level=info
        - --log.format=logfmt
        - --query.replica-label=prometheus_replica
        - --query.replica-label=rule_replica
        - --store=dnssrv+_grpc._tcp.thanos-store.thanos.svc.cluster.local
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 9099
            scheme: HTTP
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        resources: 
          {}
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120