apiVersion: v1
kind: Service
metadata:
  labels:
    component: query-layer
    name: thanos-query
  name: thanos-query
  namespace: monitoring
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    component: query-layer
    name: thanos-query