apiVersion: v1
kind: Service
metadata: 
  name: prometheus
  namespace: monitoring
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    name: prometheus
    component: server
spec:
  selector: 
    app: prometheus
    component: server
  ports: 
    - name: prometheus 
      port: 9090
      targetPort: prometheus