apiVersion: v1
kind: Service
metadata:
  labels:
    name: thanos-sidecar
  name: thanos-sidecar
  namespace: default
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    component: sidecar-layer
    name: thanos-sidecar