apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
  namespace: monitoring
  labels:
    component: database-compactor
    name: thanos-compact
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database-compactor
      name: thanos-compact
  serviceName: thanos-compact
  template:
    metadata:
      labels:
        component: database-compactor
        name: thanos-compact
    spec:
      containers:
      - name: thanos-compact
        image: quay.io/thanos/thanos:thanos:v0.13.0-rc.0
        args:
        - compact
        - --wait
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --data-dir=/var/thanos/compact
        - --debug.accept-malformed-index
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        ports:
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/thanos/compact
          name: data
          readOnly: false
      terminationGracePeriodSeconds: 120
      volumes:
      - name: storage-volume-thanos-store
        persistentVolumeClaim:
          claimName: storage-volume-thanos-store