apiVersion: v1
kind: Service
metadata:
  labels:
    component: database-compactor
    name: thanos-compact
  name: thanos-compact
  namespace: monitoring
spec:
  selector:
    component: database-compactor
    name: thanos-compact
  ports:
  - name: http
    port: 10902
    targetPort: 10902
